### ISSUE TITLE
There's no default key

### ISSUE THREAD

**Issue by edilsongudo** [arturaugusto/pyRD#1]
Hi Artur.
Congrats, this seems an interesting project

When I run app.py it asks me the key. I type 1234 but it doesn't work (like in your video). 

When I run run.py it gives me an error saying "failed to establish a connection, the request address is not a valid context"

I am not sure which script should I run first (app.py or run.py), and what is the host and port I should use in run.py?

**Comment by arturaugusto** [comment]
At the windows PC you will connect, you should run `remote.app` and provide the `addr` and `key` command line arguments.
The `addr` is the ip address of the computer running the `app.py.` If you are running both at same computer, you can use 127.0.0.1.
